---
title: IJH
timezone: America/Los_Angeles
collections:
  portfolio_items:
    title: Portfolio Items
    output: true
    permalink: "/portfolio/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  websites:
    title: Websites
    output: true
    permalink: "/websites/:path/"
  videos:
    title: Animation & Video
    output: true
    permalink: /portfolio/videos/:title/
  youtube_channels:
    output: true
    permalink: /youtube/:path/
    title: Youtube Channels
  books:
    output: true
    permalink: /books/:path/
    title: Books
  childrens_books:
    output: true
    permalink: /childrensbooks/:path/
    title: Children's Books
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
- scope:
    path: ''
    type: portfolio_items
  values:
    layout: portfolio
- scope:
    path: ''
    type: websites
  values:
    layout: website
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- github-uikit.gemspec
- vendor/
plugins:
- github-pages
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-algolia
paginate_path: "/blog/page:num/"
paginate: 20
permalink: "/:title/"
excerpt_separator: "<!--more-->"
name: Isaac Joseph Horton
author: Isaac Joseph Horton
email: isaacjosephhorton@gmail.com
description: Design and software solutions for business. Ecommerce expert. Usability
  investigator.
baseurl: ''
url: https://kre8t.github.io
avatar: "/assets/logo.png"
lang: en
locale: en_US
to_top: true
disqus: ''
twitter: kre8t_
instagram: kre8t_
github: kre8t
buymeacoffee: isaachorton
fb_app_id: ''
google_analytics: G-KZ1JS263PW
google_ad_client: pub-7840179511709652
include:
- _pages
Twitter: kre8t_
Instagram: kre8t_
GitHub: kre8t
RSS: true
markdown: kramdown
